<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="69098" started-at="2020-04-13T19:53:18Z" finished-at="2020-04-13T19:54:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="69098" started-at="2020-04-13T19:53:18Z" finished-at="2020-04-13T19:54:27Z">
      <class name="com.qtpselenium.facebook.pom.testcases.LoginTest">
        <test-method status="PASS" signature="doLogin(java.util.Hashtable)[pri:0, instance:com.qtpselenium.facebook.pom.testcases.LoginTest@1fcb4808]" name="doLogin" duration-ms="35327" started-at="2020-04-13T19:53:18Z" data-provider="getData" finished-at="2020-04-13T19:53:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=friendlyananth15@gmail.com, ExpectedResult=Success, RunMode=Y, Password=Handgreat99, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.qtpselenium.facebook.pom.testcases.LoginTest@1fcb4808]" name="quit" is-config="true" duration-ms="1040" started-at="2020-04-13T19:53:53Z" finished-at="2020-04-13T19:53:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="doLogin(java.util.Hashtable)[pri:0, instance:com.qtpselenium.facebook.pom.testcases.LoginTest@1fcb4808]" name="doLogin" duration-ms="31960" started-at="2020-04-13T19:53:54Z" data-provider="getData" finished-at="2020-04-13T19:54:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=friendlyananth15@gmail.com, ExpectedResult=Unsuccesful, RunMode=Y, Password=incorrect password, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.qtpselenium.facebook.pom.testcases.LoginTest@1fcb4808]" name="quit" is-config="true" duration-ms="733" started-at="2020-04-13T19:54:26Z" finished-at="2020-04-13T19:54:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="FAIL" signature="sendemail()[pri:0, instance:com.qtpselenium.facebook.pom.testcases.LoginTest@1fcb4808]" name="sendemail" is-config="true" duration-ms="735" started-at="2020-04-13T19:54:27Z" finished-at="2020-04-13T19:54:28Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[javax.mail.AuthenticationFailedException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: javax.mail.AuthenticationFailedException
at com.qtpselenium.facebook.pom.mail.SendMailSSLWithAttachment.sendEMail(SendMailSSLWithAttachment.java:136)
at com.qtpselenium.facebook.pom.testcases.LoginTest.sendemail(LoginTest.java:85)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.AuthenticationFailedException
at javax.mail.Service.connect(Service.java:306)
at javax.mail.Service.connect(Service.java:156)
at javax.mail.Service.connect(Service.java:105)
at javax.mail.Transport.send0(Transport.java:168)
at javax.mail.Transport.send(Transport.java:98)
at com.qtpselenium.facebook.pom.mail.SendMailSSLWithAttachment.sendEMail(SendMailSSLWithAttachment.java:130)
... 21 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendemail -->
      </class> <!-- com.qtpselenium.facebook.pom.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
